// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgDc_9LOnPu5dpvEasLjJT4WRZ_0Kqf7I',
    appId: '1:553791043014:android:666ebbaa9d2f41afdeaec7',
    messagingSenderId: '553791043014',
    projectId: 'once-aa016',
    storageBucket: 'once-aa016.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGN_XPgOj8vUhMhVapULX9p6WPS_QZggo',
    appId: '1:553791043014:ios:05f8948c08d9578adeaec7',
    messagingSenderId: '553791043014',
    projectId: 'once-aa016',
    storageBucket: 'once-aa016.appspot.com',
    androidClientId: '553791043014-iej8d56u1m0l4m46oha8qbvo54c93upv.apps.googleusercontent.com',
    iosClientId: '553791043014-cm2f08hp6k3tejggcoghaq25g9aap909.apps.googleusercontent.com',
    iosBundleId: 'com.ralphordanza.once',
  );
}
